 # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  compile:
    runs-on: agent-1
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
         
      - name: Frontend Compilation (Syntax Check)
        run: |
          cd client
          find . -name "*.js" -exec node --check {} +
          
      - name: Backend Compilation (Syntax Check)
        run: |
          cd api
          find . -name "*.js" -exec node --check {} +

  Gitleak-scan:
    runs-on: agent-1
    needs: compile
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: GitLeaks Setup
        uses: gitleaks/gitleaks-action@v2
      - name: Gitleak Scan
        run: |
          gitleaks detect --source ./client --exit-code 1
          gitleaks detect --source ./api --exit-code 1
  
  trivy_fs_sane:
    runs-on: agent-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        
